### ISSUE TITLE
useCollectionData hook reads from firestore on every keystroke when entering token on home page

### ISSUE THREAD

**Issue by nibble0101** [the-collab-lab/tcl-19-smart-shopping-list#41]
**Summary**

When a user is entering a token to join an existing list, the `onChange` event handler of the `input` field  updates the value of `existingToken` variable in state. The value of `existingToken` which changes on every keystroke as the user enters a token is also used for making a query from the `firestore` database(DB) using `useCollectionData` hook. This therefore means on every character entry, `react-firebase-hooks` will have to read from the database. It is inefficient to query the DB for the existence of a token when a user has not yet finished entering it given the fact that  there is a maximum number of document reads or writes you can make per day and  billing is done based on the number of reads/writes to the DB as well. We only need to read from the DB if a user submits the token. 

**Steps to reproduce**

To reproduce the issue,
- Pull the `jm-cu-modal-component` branch and start the app on local host using `npm run start`
- Start entering in the `input` field

**Expected results**

The DB is queried only after the user has finished entering token and submitted the `form`.

**Actual results**

- Each time you enter a character, loading spinner will appear on the screen and the `input` field will lose focus
- The loading spinner is rendered if the `loading` variable returned by `useCollectionData` is `true`. `loading` is `true` only if the DB is being queried.

**Environment**

N/A

**Comment by Amaka202** [comment]
This issue has been fixed. By taking out the `useCollectionData` hook and querrying the database only when the user is done inputing the token
